spring.application.name=api-gateway
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8080/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webmvc.routes[0].id=doctor-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/doctors/**

spring.cloud.gateway.server.webmvc.routes[1].id=appointment-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/appointments/**

spring.cloud.gateway.server.webmvc.routes[2].id=patient-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/patients/**

spring.cloud.gateway.server.webmvc.routes[3].id=notification-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/notifications/**

spring.cloud.gateway.server.webmvc.routes[4].id=billing-service
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/billing/**

spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webmvc.globalcors.add-to-simple-url-handler-mapping=true