spring.application.name=patient-service

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8080/eureka

spring.datasource.url=jdbc:mysql://localhost:3306/patient_db
spring.datasource.username=root
spring.datasource.password=Yashu@168

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true